name: Build App with Maven and deploy it onto an SFTP server

on:
  workflow_call:
    inputs:
      sftp_target_dir:
        required: true
        type: string
      release_version:
        required: false
        type: string
      artifact_id:
        required: false
        type: string
      project_id:
        required: true
        type: string
      username:
        required: true
        type: string
      server:
        required: true
        type: string
      suffix:
        required: false
        type: string
        default: ""
    secrets:
      gcp_artifactory_service_account:
        required: true
      deploy_ssh_key:
        required: true
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set tag as environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set GCP project id as environment variable
        run: echo "GCP_PROJECT=${{ inputs.project_id }}" >> $GITHUB_ENV
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_ARTIFACTORY_SERVICE_ACCOUNT}}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set Artifact ID
        run: echo "ARTIFACT_ID=$( mvn help:evaluate -Dproject.gcp-project=${{ inputs.project_id }} -Dexpression=project.artifactId -q -DforceStdout )" >> $GITHUB_ENV
      - name: Set Artifact name
        run: |
          if [ "${{ inputs.suffix }}" == "" ]; then
            echo "ARTIFACT_NAME=${{ env.ARTIFACT_ID }}-${{ env.RELEASE_VERSION }}.jar" >> $GITHUB_ENV
          else
            echo "ARTIFACT_NAME=${{ env.ARTIFACT_ID }}-${{ env.RELEASE_VERSION }}-${{ inputs.suffix }}.jar" >> $GITHUB_ENV
          fi
      - name: Set Artifact link name
        run: |
          if [ "${{ inputs.suffix }}" == "" ]; then
            echo "ARTIFACT_LINK=${{ env.ARTIFACT_ID }}.jar" >> $GITHUB_ENV
          else
            echo "ARTIFACT_LINK=${{ env.ARTIFACT_ID }}-${{ inputs.suffix }}.jar" >> $GITHUB_ENV
          fi
      - name: Print variables
        run: |
          echo ${{ env.RELEASE_VERSION }}
          echo ${{ env.ARTIFACT_ID }}
          echo ${{ env.ARTIFACT_NAME }}
          echo ${{ env.ARTIFACT_LINK }}
      - name: Set version by tag
        run: mvn versions:set "-DnewVersion=${{ env.RELEASE_VERSION }}"
      - name: Build with Maven
        run: mvn clean install "-Dproject.gcp-project=${{ inputs.project_id }} -DskipTests"
      - name: Deploy artifact to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ inputs.username }}
          server: ${{ inputs.server }}
          ssh_private_key: ${{ secrets.deploy_ssh_key }}
          local_path: 'target/${{ env.ARTIFACT_ID }}-${{ env.RELEASE_VERSION }}.jar'
          remote_path: '${{ inputs.sftp_target_dir }}/releases/${{ env.ARTIFACT_NAME }}'
      - name: Update symlink for current version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ inputs.server }}
          username: ${{ inputs.username }}
          key: ${{ secrets.deploy_ssh_key }}
          script: 'cd ${{ inputs.sftp_target_dir }}/apps && ln -sf ../releases/${{ env.ARTIFACT_NAME }} ${{ env.ARTIFACT_LINK }} '
