name: Build App with Maven and deploy it onto an SFTP server

on:
  workflow_call:
    inputs:
      project_id:
        required: true
        type: string
    secrets:
      gcp_artifactory_service_account:
        required: true
      maven_secret:
        required: true
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set tag as environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set GCP project id as environment variable
        run: echo "GCP_PROJECT=${{ inputs.project_id }}" >> $GITHUB_ENV
      - name: Print tag version
        run: echo ${{ env.RELEASE_VERSION }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ inputs.project_id }}
          service_account_key: ${{ secrets.gcp_artifactory_service_account }}
          export_default_credentials: true
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set version by tag
        run: mvn versions:set "-DnewVersion=${{ env.RELEASE_VERSION }}"
      - name: Build with Maven
        run: mvn clean install "-DskipTests"
      - name: Deploy artifact to GCP Artifact Repository
        run: mvn deploy --settings=settings.xml "-DskipTests"
        env:
          MAVEN_SECRET: ${{ secrets.maven_secret }}
