name: Manual deploy trigger for dag files

on:
  workflow_call:
    inputs:
      server:
        required: true
        type: string
      username:
        required: true
        type: string
      port:
        required: false
        type: number
        default: 2022
    secrets:
      deploy_ssh_key:
        required: true

jobs:
  deploy-dags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current master branch
        uses: actions/checkout@v2

      - name: Fail if branch is not master
        if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/master'
        run: |
          echo "This workflow can not be triggered with workflow_dispatch on a branch other than master"
          exit 1

      - name: Import SSH Key
        run: |
          echo "${{ secrets.deploy_ssh_key }}" > private_key
          chmod 600 private_key

      - uses: andreiio/rclone-action@v1
        with:
          args: "sync ./projects :sftp:projects --include *.py"
        env:
          RCLONE_SFTP_HOST: ${{ inputs.server }}
          RCLONE_SFTP_PORT: ${{ inputs.port }}
          RCLONE_SFTP_USER: ${{ inputs.username }}
          RCLONE_SFTP_KEY_FILE: private_key
          RCLONE_SFTP_DISABLE_HASHCHECK: true

      - uses: techdivision-rnd/github-templates/.github/workflows/deployment-notification.yml@master
