name: Deployment Notification

on:
  workflow_call:

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      CHAT_WEBHOOK: ${{ secrets.NOTIFY_WEBHOOK }}
      REPOSITORY: ${{ github.repository }}
      TAG_NAME: ${{ github.ref_name }}
      COMMIT_SHA: ${{ github.sha }}
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Send notification to webhook
      run: |
        curl -X POST -H 'Content-type: application/json' --data \
        '{
          "cards": [
            {
              "header": {
                "title": "GitHub Actions",
                "subtitle": "Deployment Notification",
                "imageUrl": "https://raw.githubusercontent.com/github/explore/2c7e603b797535e5ad8b4beb575ab3b7354666e1/topics/actions/actions.png",
                "imageStyle": "AVATAR"
              },
              "sections": [
                {
                  "widgets": [
                    {
                      "keyValue": {
                        "topLabel": "Pipeline",
                        "content": "'"$REPOSITORY"'"
                      }
                    },
                    {
                      "keyValue": {
                        "topLabel": "Version",
                        "content": "'"$TAG_NAME"'"
                      }
                    },
                    {
                      "keyValue": {
                        "topLabel": "Description",
                        "content": "'"$COMMIT_MESSAGE"'"
                      }
                    }
                  ]
                },
                {
                  "widgets": [
                    {
                      "buttons": [
                        {
                          "textButton": {
                            "text": "VIEW REPOSITORY",
                            "onClick": {
                              "openLink": {
                                "url": "https://github.com/'"$REPOSITORY"'"
                              }
                            }
                          }
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }' $CHAT_WEBHOOK
