name: Deployment Notification

on:
  workflow_call:

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ github.repository }}
      TAG_NAME: ${{ github.ref_name }}
    steps:
    - name: Send notification to webhook
      run: |
        curl -X POST -H 'Content-type: application/json' --data \
        '{
          "cards": [
            {
              "header": {
                "title": "GitHub Actions",
                "subtitle": "Deployment Notification",
                "imageUrl": "https://raw.githubusercontent.com/github/explore/2c7e603b797535e5ad8b4beb575ab3b7354666e1/topics/actions/actions.png",
                "imageStyle": "AVATAR"
              },
              "sections": [
                {
                  "widgets": [
                    {
                      "keyValue": {
                        "topLabel": "Component",
                        "content": "'"$REPOSITORY"'"
                      }
                    },
                    {
                      "keyValue": {
                        "topLabel": "Version",
                        "content": "'"$TAG_NAME"'"
                      }
                    },
                    {
                      "textParagraph": {
                        "text": "<a href=\"https://github.com/'"$REPOSITORY"'/releases/tag/'"$TAG_NAME"'\">View Release Notes</a>"
                      }
                    }
                  ]
                }
              ]
            }
          ]
        }' ${{ secrets.NOTIFY_WEBHOOK }}
