name: Execute java tests over maven

on:
  workflow_call:
    inputs:
      database_name:
        required: true
        type: string
      project_id:
        required: true
        type: string
    secrets:
      gcp_artifactory_service_account:
        required: true

jobs:
  maven_tests:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017
        
    steps:
    - uses: actions/checkout@v3
    - name: Setup mongo tools
      uses: boly38/action-mongo-tools@stable
    - name: Mongo-shell usage - setup mongo user
      run: |
        mongosh admin --eval "use ${{ inputs.database_name }};"
    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'
        cache: 'maven'
    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        project_id: ${{ inputs.project_id }}
        credentials_json: ${{ secrets.GCP_ARTIFACTORY_SERVICE_ACCOUNT}}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - name: Test with Maven
      run: mvn test
