name: Create Test Workflow

on:
  workflow_call:
    inputs:
      customer:
        required: true
        type: string
    secrets:
      username:
        required: true

jobs:
  do-something-else:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello {{ secrets.username }}! Repo for customer {{ inputs.customer }}"
